pool:
  vmImage: 'ubuntu-22.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6.0 SDK'
  inputs:
    version: '6.0.x'
    includePreviewVersions: false

- script: dotnet --version
  displayName: 'Check .NET SDK version'
  
- task: DotNetCoreCLI@2
  displayName: 'Restore & Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet package'
  inputs:
    command: 'pack'
    projects: '**/*.csproj'
    arguments: '--no-build --configuration $(buildConfiguration)'
    versioningScheme: byEnvVar
    versionEnvVar: packageVersion

- task: NuGetCommand@2
  displayName: 'Publish NuGet package'
  inputs:
    command: push
    feedPublish: 'Tailspin.SpaceGame.Web.Models' # Replace with your feed name
    allowPackageConflicts: true
  condition: succeeded()
