pool:
  vmImage: 'ubuntu-22.04'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '6.0.x'
  packageVersion: '1.0.0'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'
    performMultiLevelLookup: true
    includePreviewVersions: false

- task: DotNetCoreCLI@2
  displayName: 'Restore & Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet package'
  inputs:
    command: 'pack'
    projects: '**/*.csproj'
    arguments: '--no-build --configuration $(buildConfiguration)'
    versioningScheme: byEnvVar
    versionEnvVar: packageVersion

- task: NuGetCommand@2
  displayName: 'Publish NuGet package'
  inputs:
    command: push
    feedPublish: 'Tailspin.SpaceGame.Web.Models' # Replace with your feed name
    allowPackageConflicts: true
  condition: succeeded()
